### ISSUE TITLE
depends on missing termios.h

### ISSUE THREAD

**Issue by bobemoe** [DMRodrigues/arduino-i2c-read-eeprom#1]
Where can I get this missing library?

**Comment by DMRodrigues** [comment]
Which OS are you using?

**Comment by bobemoe** [comment]
Oh is it not an Ardunio Library? The OS is Linux (Devuan, Debian based)

**Comment by DMRodrigues** [comment]
i2c_read_eeprom.ino is the arduino sketch that must be compiled in Arduino IDE.
i2c_read_eeprom.c is a C program that must be compiled with gcc on your Linux PC. You can also use Makefile to compile the C program.

**Comment by bobemoe** [comment]
Hmm, I can't get either to compile. 

Starting with the .ino I get: 

```plain
i2c_read_eeprom.c:29:21: error: termios.h: No such file or directory
compilation terminated.
exit status 1
termios.h: No such file or directory
```

and with the .c I get

```plain
$ make
gcc -Wall i2c_read_eeprom.c -o i2c_read_eeprom
/tmp/ccvDpU9u.o: In function `print_usage':
i2c_read_eeprom.c:(.text+0x23e): undefined reference to `print_eeprom'
collect2: error: ld returned 1 exit status
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 1
```

I guess the .ino needs to compile first? So we are back to the missing termios.h

I still cant see where to get this library from?? I have done lots of search and do see a few references to it. 

So is it a arduino library that needs to go into ~/sketchbook/libraries/ or is it a system library.  I have done a search of my apt-get package manager and it looks like libc6-dev:amd64 provides /usr/include/termios.h which is installed but still no luck.

Should I symlink this to sketchbook/libraries or change the include path in the .ino?

Thanks

**Comment by DMRodrigues** [comment]
Only the i2c_read_eeprom.ino is compiled in the **arduino IDE** (it seems that you are also trying to compile the C program in the arduino IDE).

Then i2c_read_eeprom.c must be compiled with Makefile and make sure eeprom.h is in he same folder/path, since `print_eeprom' is defined in that header file.

BR,
DMR

**Comment by Yarokot** [comment]
I have that same problem as bobemoe with compile i2c_read_eeprom.c, "undefined reference to 'print_eeprom', epprom.h is in the same folder with i2_read_eeprom.c. I do this in console/gcc, makefile and command 'gcc i2c_read_eeprom.c'. I tried another OS Debian, Ubuntu, Xubuntu. I emulate OS on VMware. Maybe that a problem?

EDIT:
So, I delete 'inline' in front of 'void print_eeprom()' in eeprom.h and compiled correct. But doesn't read eeprom correctly. Do you know which command I must use to read eeprom 24c01?

**Comment by DMRodrigues** [comment]
Yes, you're right, some compilers might not like 'inline' and for sure it's no C89 compliant (my bad 😞 )

Regarding the read of EEPROM 24C01, it's protocol is not implemented. The main problem is when you call beginTransmission() with the address of the device not correctly calculated. Therefore, it needs to be changed, for that there's a few examples on the internet how to read such devices and the changes should be minimal!

**Comment by condemil** [comment]
I had the same issue, you need to remove `inline` from the `eeprom.h`
