### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Maxx-W** [DMRodrigues/arduino-i2c-read-eeprom#2]
I get the following error when I try to run make:

`gcc -Wall i2c_read_eeprom.c -o i2c_read_eeprom
Undefined symbols for architecture x86_64:
  "_print_eeprom", referenced from:
      _print_usage in i2c_read_eeprom-71600c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1
`

**Comment by DMRodrigues** [comment]
Hi,
pull the latest changes and try to compile again.
